name: Alerta no Discord

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  discord-alert:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar alerta para o Discord
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"content": "🚀 Novo commit ou merge no branch `main`! Verifique o repositório."}' \
          ${{ secrets.DISCORD_WEBHOOK }}
